<a href="https://colab.research.google.com/github/SANGRAMLEMBE/Neural_Networks_from_scratch_in_python/blob/main/coding_our_first_neurons.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Coding Our First Neurons

In [1]:
# Neuron with 3 inputs
input = [1,2,3]

weights  = [0.2,0.8,-0.5]

bias= 2

output = (input[0]*weights[0])+(input[1]*weights[1])+(input[2]*weights[2])+bias

print(output)

2.3


In [2]:
# Neuron with 4 inputs
input = [1,2,3,4]

weights  = [0.2,0.8,0.4,-0.5]

bias= 2

output = (input[0]*weights[0])+(input[1]*weights[1])+(input[2]*weights[2])+ (input[3]*weights[3])+bias

print(output)

3.0


In [3]:
#Layer of Neurons

inputs = [1,2,3,2.5]

weights = [[0.2,0.8,-0.5,1],
           [0.5,-0.91,0.26,-0.5],
           [-0.26,-0.27,0.17,0.87]]

biases = [2,3,0.5]

bias1 = 2
bias2 = 3
bias3 = 0.5

output = [ # Neuron 1
          inputs[0]*weights[0][0]+       #
           inputs[1]*weights[0][1]+
           inputs[2]*weights[0][2]+
           inputs[3]*weights[0][3]+
           bias1,
           # Neuron 2
           inputs[0]*weights[1][0]+
           inputs[1]*weights[1][1]+
           inputs[2]*weights[1][2]+
           inputs[3]*weights[1][3]+
           bias2,
           # Neuron 3
           inputs[0]*weights[2][0]+
           inputs[1]*weights[2][1]+
           inputs[2]*weights[2][2]+
           inputs[3]*weights[2][3]+
           bias3]

print(output)

[4.8, 1.21, 2.385]


In [4]:
#Layer of Neurons

inputs = [1,2,3,2.5]

weights = [[0.2,0.8,-0.5,1],
           [0.5,-0.91,0.26,-0.5],
           [-0.26,-0.27,0.17,0.87]]

weight1 = weights[0]     # List of Weights associated with 1st Neuron
weight2 = weights[1]     # List of Weights associated with 2nd Neuron
weight3 = weights[2]     # List of Weights associated with 3rd Neuron

biases = [2,3,0.5]

bias1 = 2
bias2 = 3
bias3 = 0.5

output = [ # Neuron 1
          inputs[0]*weight1[0]+
           inputs[1]*weight1[1]+
           inputs[2]*weight1[2]+
           inputs[3]*weight1[3]+
           bias1,
           # Neuron 2
           inputs[0]*weight2[0]+
           inputs[1]*weight2[1]+
           inputs[2]*weight2[2]+
           inputs[3]*weight2[3]+
           bias2,
           # Neuron 3
           inputs[0]*weight3[0]+
           inputs[1]*weight3[1]+
           inputs[2]*weight3[2]+
           inputs[3]*weight3[3]+
           bias3]

print(output)

[4.8, 1.21, 2.385]


# Using Loops for Better And Easier Coding


In [5]:
inputs = [1.1,2.2,3.3]

# List of Weights

weights = [[2,0,0],
           [2,2,0],
           [2,2,2]]

# List of bias
biases = [0,0,1]

# Output of Current Layer

layer_output = []

# For each Neuron
for neuron_weights , neuron_bias in zip(weights,biases):
  # Zeroed Output of given Neuron
  neuron_output = 0
  # For each input and Weights to the Neuron
  for n_input,weight in zip(inputs,neuron_weights):
    neuron_output += n_input*weight    # w11*x1 + W12*x2 + w13*x3 +w14*x4  / w21*x1 + W22*x2 + w23*x3 +w24*x4
    neuron_output += neuron_bias       #  w11*x1 + W12*x2 + w13*x3 +w14*x4+b1
  layer_output.append(neuron_output)

print(layer_output)


[2.2, 6.6000000000000005, 16.200000000000003]


In [6]:
inputs = [1,2,3,2.5]

# List of Weights

weights = [[0.2,0.8,-0.5,1],
           [0.5,-0.91,0.26,-0.5],
           [-0.26,-0.27,0.17,0.87]]

# List of bias
biases = [2,3,0.5]


# Output of Current Layer

layer_output = []

# For each Neuron
for neuron_weights , neuron_bias in zip(weights,biases):
  # Zeroed Output of given Neuron
  neuron_output = 0
  # For each input and Weights to the Neuron
  for n_input,weight in zip(inputs,neuron_weights):
    # Multipy  this input by associated weight
    # and add to the neuron's output variables

    neuron_output += n_input*weight    # w11*x1 + W12*x2 + w13*x3 +w14*x4  / w21*x1 + W22*x2 + w23*x3 +w24*x4


  # for Biases ( must hhave to keep it outside the for loop of weight)
  neuron_output += neuron_bias       #  w11*x1 + W12*x2 + w13*x3 +w14*x4+b1
  layer_output.append(neuron_output)

print(layer_output)


[4.8, 1.21, 2.385]


# The Numpy and Dot product in coding neurons and Layers

1. Vector to Vector Dot Product
In neural networks, the vector-vector dot product is often used for operations like computing similarities or simple perceptron activations. It calculates a scalar as the sum of element-wise products. For vectors a = [a1, a2, ..., an] and b = [b1, b2, ..., bn], it is:
dot(a, b) = sum over i of (a_i * b_i)
Vectors must have matching lengths.

2. Vector to Matrix Dot Product
This is common in neural networks for layer computations, such as multiplying an input vector by a weight matrix to get activations for multiple neurons. It performs a sum product, yielding a vector where each element is the dot product of the vector with a row of the matrix. For vector v (shape (n,)) and matrix M (shape (m, n)), the result (shape (m,)) has:
result[i] = sum over j of (M[i, j] * v[j])
The vector length must match the matrix's columns.


3. Matrix to Matrix Dot Product
In neural networks from scratch, matrix-matrix dot products are key for batch processing (e.g., input matrix dotted with weight matrix for multiple samples). It performs matrix multiplication, where each element in the result is a dot product of a row from the first matrix and a column from the second. For matrices A (shape (m, p)) and B (shape (p, n)), result C (shape (m, n)) has:
C[i, j] = sum over k of (A[i, k] * B[k, j])
Columns of A must match rows of B

np.dot(a,b) != np.dot(b,a)

In [8]:
import numpy as np
inputs = [1.0,2.0,3.0,2.5]
weights =[0.2,0.8,-0.5,1.0]
bias = 2.0
outputs = np.dot(weights,inputs)+bias
print(outputs)

4.8


In [11]:
input = [1,2,3]

weights  = [0.2,0.8,-0.5]

bias= 2

output = np.dot(weights,input)+bias

print(output)

2.3


## Dot product between Vector and Matrix

[np.dot(w1,x)+b1 , np.dot(w2,x)+ b2 , np.dot(w3 + x) +b3 ]

In [15]:
inputs = [1,2,3,2.5]
biases = [2,3,0.5]

weights = [[0.2,0.8,-0.5,1],
           [0.5,-0.91,0.26,-0.5],
           [-0.26,-0.27,0.17,0.87]]

weight1 = weights[0]     # List of Weights associated with 1st Neuron
weight2 = weights[1]     # List of Weights associated with 2nd Neuron
weight3 = weights[2]     # List of Weights associated with 3rd Neuron


output = [np.dot(weight1,inputs)+biases[0] , np.dot(weight2,inputs)+biases[1] , np.dot(weight3,inputs)+biases[2]]

print(output)

[np.float64(4.8), np.float64(1.21), np.float64(2.385)]


In [16]:
# LAYER CODING

inputs = [1,2,3,2.5]
biases = [2,3,0.5]

weights = [[0.2,0.8,-0.5,1],
           [0.5,-0.91,0.26,-0.5],
           [-0.26,-0.27,0.17,0.87]]

layer_output = np.dot(weights,inputs)+biases

print(layer_output)

[4.8   1.21  2.385]


Inputs = 3 Rows * 4 Columns

weights = 3 Rows * 4 Columns

we can't do matrix multiplication , so we have to Transpose weight Matrix

output (3,3) = Inputs(3,4) * T(Weights)(4,3)

In [17]:
# BATCH CODING

inputs =   [1,2,3,2.5],[2,5,-1,2],[-1.5,2.7,3.3,-0.8]

biases = [2,3,0.5]

weights = [[0.2,0.8,-0.5,1],
           [0.5,-0.91,0.26,-0.5],
           [-0.26,-0.27,0.17,0.87]]

# here our weights are in list so we have to convert list into array.
outputs = np.dot(inputs,np.array(weights).T) + biases
print(outputs)



[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
