<a href="https://colab.research.google.com/github/SANGRAMLEMBE/Neural_Networks_from_scratch_in_python/blob/main/4_Broadcasting_and_array_summation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [3]:
# Array Summation
A =  [[1, 2, 3],[4, 5,6],[7,8,9]]
print(np.sum(A))

45


In [15]:
# 1 Dimensional array
print(np.sum(A, axis = 0))
print(np.sum(A, axis = 0).shape)

[12 15 18]
(3,)


In [5]:
# 1 Dimensional array
print(np.sum(A, axis = 1))
print(np.sum(A, axis = 1).shape)

[ 6 15 24]
(3,)


In [10]:
# 2 Dimensional array  Broadcasting
print(np.sum(A, axis =1, keepdims=True))
print(np.sum(A, axis=1, keepdims= True).shape)

[[ 6]
 [15]
 [24]]
(3, 1)


In [12]:
# 2 Dimensional array Broadcasting
print(np.sum(A, axis =0, keepdims=True))
print(np.sum(A, axis=0, keepdims= True).shape)

[[12 15 18]]
(1, 3)


In [14]:
print("Max values in columns",np.max(A, axis = 0))
print("Max values in Rows",np.max(A, axis = 1))

Max values in columns [7 8 9]
Max values in Rows [3 6 9]
