<a href="https://colab.research.google.com/github/SANGRAMLEMBE/Neural_Networks_from_scratch_in_python/blob/main/Coding_multiple_neural_network_layers_and_stacking_together.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

-  Always we have to take (weight * input) format only. but , dot product is not happend then we have to take (input * [weight]Transpose)


In [7]:

inputs =  [ [1,2,3,2.5],
             [2,5,-1,2],
              [-1.5,2.7,3.3,-0.8]]

biases = [2,3,0.5]

weight1 = [[0.2,0.8,-0.5,1],
           [0.5,-0.91,0.26,-0.5],
           [-0.26,-0.27,0.17,0.87]]

biases = [2,3,0.5]

weight2 = [[0.1,-0.14,0.5],
           [-0.5,0.12,-0.33],
           [-0.44,0.73,-0.13]
          ]

biases2 = [-1,2,-0.5]

# convert list to Numpy array

inputs_array = np.array(inputs)
weights1_array = np.array(weight1)
weights2_array = np.array(weight2)
biases_array = np.array(biases)
biases2_array = np.array(biases2)


# calculate the output of the first layer
layer1_output = np.dot(inputs_array, weights1_array.T) + biases_array
print(layer1_output)

# calculate the output of the second layer
layer2_output = np.dot(layer1_output, weights2_array.T) + biases2_array
print("\nFinal output matrix \n",layer2_output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]

Final output matrix 
 [[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [19]:
# Create 4 hidden layer Network and find what is output Matrix

input = [[1,2,3,2.5],
         [3.5,6,1.7,5.6],
         [5,6,2,0.7],
         [2.5,3.6,4,5]]

weight1 = [[0.2,0.8,-0.5,1],
           [0.5,-0.91,0.26,-0.5],
           [-0.26,-0.27,0.17,0.87],
            [5,6,2,0.7]]

weight2 = [[0.1,-0.14,0.5,2],
           [-0.5,0.12,-0.33,0.5],
           [-0.44,0.73,-0.13,0.8],
            [-0.44,0.73,-0.13,2]
          ]

weight3 = [[-0.27,0.17,0.87,0.5],
           [0.1,-0.14,0.5,0.8],
           [-0.5,8,-0.33,1],
           [-0.44,0.73,-0.13,0.45]
          ]

weight4 = [[0.1,-0.14,0.5,0.1],
           [-0.5,0.12,-0.33,0.95],
           [-0.44,0.73,-0.13,0.7],
           [0.1,-0.14,0.5,0.1]
          ]

bias1 = [1,2,0.2,1]
bias2 = [1,2,0.2,1]
bias3 = [1,2,0.2,1]
bias4 = [1,2,0.2,1]

input_array = np.array(input)
weight1_array = np.array(weight1)
weight2_array = np.array(weight2)
weight3_array = np.array(weight3)
weight4_array = np.array(weight4)
bias1_array = np.array(bias1)
bias2_array = np.array(bias2)
bias3_array = np.array(bias3)
bias4_array = np.array(bias4)

layer1_output = np.dot(weight1_array, input_array) + bias1_array
print("\nFirst Hidden Layer output\n",layer1_output)
layer2_output = np.dot(weight2_array,layer1_output) + bias2_array
print("\nSecound Hidden Layer Output\n",layer2_output)
layer3_output = np.dot(weight3_array,layer2_output) + bias3_array
print("\nThird Hidden Layer Output\n",layer3_output)
layer4_output = np.dot(weight4_array,layer3_output) + bias4_array
print("\nOutput Layer\n",layer4_output)


First Hidden Layer output
 [[ 4.     7.8    5.16  10.63 ]
 [-1.635 -2.7   -1.327 -5.164]
 [ 2.82   4.012  2.781  3.307]
 [38.75  62.52  32.2   52.   ]]

Secound Hidden Layer Output
 [[ 80.5389  130.204    66.69228 108.43946]
 [ 17.2482   27.71204  12.64303  19.97401]
 [ 28.67985  46.09144  22.35936  33.72317]
 [ 75.17985 121.11544  60.99936  96.12317]]

Third Hidden Layer Output
 [[ 44.7280855  72.2132396  34.2947227  52.5176704]
 [ 81.122947  131.0787864  65.0783718 102.8077056]
 [164.4316495 264.4995848 121.6188712 191.5668739]
 [  8.256622   13.45009     4.6278039   6.7390793]]

Output Layer
 [[ 77.15708292 124.46509526  55.79071621  88.31603314]
 [-58.04794254 -92.88444292 -44.87577053 -69.73685358]
 [ 24.94291466  40.94380562  20.0465429   32.75551201]
 [ 77.15708292 124.46509526  55.79071621  88.31603314]]
